name: win75
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.5
  image_cropper: ^1.2.1
  shared_preferences: ^0.5.7
  font_awesome_flutter: ^8.8.1
  flutter_inner_drawer: ^0.5.6+1
  carousel_slider: ^2.0.0
  http: ^0.12.1
  dio: ^3.0.9
  firebase_core: ^0.4.5
  connectivity: ^0.4.8+6
  true_time: ^0.1.0
  provider: ^4.0.5+1
  ntp: ^1.0.6
  flutter_secure_storage: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#  assets:
#   - assets/images
  fonts:
    - family: EcommerceAppUI
      fonts:
        - asset: assets/fonts/EcommerceAppUI.ttf
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Bold.ttf
        - asset: assets/fonts/Karla-Regular.ttf
        - asset: assets/fonts/Karla-BoldItalic.ttf
        - asset: assets/fonts/Karla-Italic.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
